#################### SIMULADOR DE MÉDIA ENEM ####################
print("Bem vindo ao simulador de notas do Enem. Por favor, insira as suas notas abaixo.")
n = input("Qual foi a sua nota em CIÊNCIAS DA NATUREZA?" )
m = input("Qual foi a sua nota em MATEMÁTICA? " )
l = input("Qual foi a sua nota em LINGUAGENS? ")
h = input("Qual foi a sua nota em CIÊNCIAS HUMANAS? ")
r = input("Qual foi a sua nota na REDAÇÃO? ")
print("Ótimo! Agora insira o nome da universidade desejada e depois os pesos que ela atribui para cada área do conhecimento.")
u = input("Qual universidade você pretende ingressar? ")
n1 = input("Qual o peso que a {u} dá para CIÊNCIAS DA NATUREZA? ")
m1 = input("Qual o peso que a {u} dá para MATEMÁTICA? ")
l1 = input("Qual o peso que a {u} dá para LINGUAGENS? ")
h1 = input("Qual o peso que a {u} dá para CIÊNCIAS HUMANAS? ")
r1 = input("Qual o peso que a {u} dá para REDAÇÃO? ")
resultado = ((n*n1) + (m*m1) + (l*l1) (h*h1) + (r*r1))/(n1+m1+l1+h1+r1)
print(f"Bem, com os valores fornecidos acima, a sua média ponderada das notas do Enem para esse curso é {resultado:,.2f}.")
